services:
  user-service:
    build: ./user-service-focusx
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGODB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    env_file:
      - .env  

  goal-service:
    build: ./goal-service-focusx
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=${MONGODB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    env_file:
      - .env  
 

  session-service:
    build: ./session-service-focusx
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=${MONGODB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    env_file:
      - .env  

